### ISSUE TITLE
package ‘pophelper’ is not available (for R version 3.6.1)

### ISSUE THREAD

**Issue by vincenzolandi** [royfrancis/pophelperShiny#1]
Hello I am installing pophelperShiny but i received by R this message "package ‘pophelper’ is not available (for R version 3.6.1)" but in the web page it seem that windows +R 3.6.1 are compatibles...Should I get back to 3.6?
Thank you!

**Comment by royfrancis** [comment]
It should work with 3.6.1. Do not try to install from CRAN. ie; From RStudio packages tab or `install.packages()`. You should install as instructed here: http://royfrancis.github.io/pophelperShiny/

**Comment by vincenzolandi** [comment]
> It should work with 3.6.1. Do not try to install from CRAN. ie; From RStudio packages tab or `install.packages()`. You should install as instructed here: http://royfrancis.github.io/pophelperShiny/

it work in Rstudio! Thank a lot! Great package!
